basePath: /api
definitions:
  backend.versionInfo:
    properties:
      build_date:
        type: string
      build_ref:
        type: string
      version:
        type: string
    type: object
  jwk.Set:
    type: object
info:
  contact:
    email: dev@oidc-client
    name: API Support
  description: Swagger API oidc-client
  termsOfService: http://swagger.io/terms/
  title: oidc-client
paths:
  /v1/auth:
    get:
      description: Starts the flow
      produces:
      - application/json
      responses:
        "302":
          description: ""
      summary: Starts the flow
      tags:
      - Misc
  /v1/callback:
    get:
      description: Callback handler
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Callback handler
      tags:
      - Misc
  /v1/jwks:
    get:
      description: Returns our JWKS so that our signatures can be verified
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/jwk.Set'
      summary: Returns our JWKS so that our signatures can be verified
      tags:
      - Misc
  /v1/version:
    get:
      description: Returns version information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend.versionInfo'
      summary: Returns version information
      tags:
      - Misc
swagger: "2.0"
